[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[edge_functions]
  directory = "netlify/edge-functions"

# Only one edge function mapping block
[[edge_functions]]
  path = "/*"
  function = "basic-auth"
